name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * * #8:00 AM IST
    - cron: 00 14 * * * #7:00 PM IST
    - cron: 00 06 * * 1-5
jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v5.1.0

      - name: Install Nodjs and npm
        uses: actions/setup-node@v6.5.0
        with:
          node-version: '22'

      - name: Install Newman and Html-extra globally
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra
            
      - name: Run the newman collection with newman
        run: |
             newman run 'Inwarranty -flow collection.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testdata.csv \
             -r cli,htmlextra








            
          
    
